author:
  name: Joe Masilotti
  email: joe@masilotti.com
  github: joemasilotti
  linkedin: joemasilotti
  twitter: joemasilotti
exclude:
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
  - .gitignore
  - resources
include:
  - .htaccess
  - _newsletters
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-purgecss
url: https://masilotti.com

# jekyll-seo-tag configuration
title: Masilotti.com
tagline: "iOS, Ruby on Rails, and testing. Maybe even a bit on board games."
description: "A blog from Joe Masilotti, an independent developer who's passionate about clean, testable code."
logo: images/avatar-circle.png
twitter:
  username: joemasilotti
  card: summary_large_image
social:
  name: Joe Masilotti
  links:
    - https://twitter.com/joemasilotti
    - https://www.linkedin.com/in/joemasilotti
    - https://github.com/joemasilotti
