# Github Pages Config
domain: divashen.github.io
url: https://divashen.github.io
baseurl: /divashen.com

# Jekyll configuration
title: divashen.com
description:
author:
  name: Divashen Govender
  email: ''
  twitter: divasheng
  github: divasheng
  linkedin: divasheng

# Files to exclude from the generated site
exclude:
  - README.md
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

# Page configuration
permalink: /:title/
collections:
  pages:
    output: true
    permalink: /:path/
  hotwire:
    output: true
    permalink: /hotwire/edition-:title/
defaults:
  - scope:
      path: _posts/
      type: posts
    values:
      layout: post
      back: _pages/articles.liquid
      preview_links_template_id: 999
  - scope:
      path: _posts/turbo-ios
      type: posts
    values:
      permalink: /turbo-ios/:title/
      back: _posts/2021-05-14-turbo-ios.md
  - scope:
      path: _hotwire/
      type: hotwire
    values:
      layout: hotwire
      back: _pages/newsletter.liquid
      preview_links_template_id: 1000
      og_title: ⚡️ Hotwire Monthly newsletter

# Plugin configuration
plugins:
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-inline-svg
postcss:
  cache: false
