# Build settings
url: https://masilotti.com
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss

author:
  email: joe@masilotti.com
  github: joemasilotti
  linkedin: joemasilotti
  twitter: joemasilotti

# jekyll-seo-tag configuration
title: Masilotti.com
tagline: "iOS, Ruby on Rails, and testing. Maybe even a bit on board games."
description: "A blog from Joe Masilotti, an independent developer who's passionate about clean, testable code."
twitter:
  username: joemasilotti
  card: summary_large_image
logo: images/logo.png

exclude:
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
  - .gitignore
  - resources
