development:
  url: https://localhost:4000
  fathom_site_id: FWVZGVUN
  future: true

staging:
  url: https://dev.masilotti.com
  fathom_site_id: FWVZGVUN

production:
  url: https://masilotti.com
  fathom_site_id: QNURQQHD

previewify_site_id: 755

# TODO: Move to config/initializers.rb.
collections:
  hotwire:
    sort_direction: descending
    output: true
  snippets:
    output: false

# TODO: Move to config/initializers.rb.
feed:
  collections:
    hotwire:
      path: /hotwire.xml

# TODO: Categories, tags, or custom taxonomies for turbo-ios series.
# https://www.bridgetownrb.com/docs/resources#taxonomies
